package com.soufiane.json_to_objetct.model;

import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Arrays;
import java.util.List;

public class MediaVocal implements IMedia {
    private String CVO = "";
    private String LINE_TYPE = "MEDIA";
    private String MEDIA_TYPE = "";
    private String SUBSCRIPTION_PRICE = "";
    private String COMMISSIONING_PRICE = "";
    private String USAGE_PRICE_FIX = "";
    private String USAGE_PRICE_MOBILE = "";
    private String USAGE_PRICE_ABOUTE = "";
    private String FIRST_DEGRESSION_LEVEL = "";
    private String FIRST_DEGRESSION_LEVEL_VALUE_FIX = "";
    private String FIRST_DEGRESSION_LEVEL_VALUE_MOBILE = "";
    private String FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE = "";
    private String SECOND_DEGRESSION_LEVEL = "";
    private String SECOND_DEGRESSION_LEVEL_VALUE_FIX = "";
    private String SECOND_DEGRESSION_LEVEL_VALUE_MOBILE = "";
    private String SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE = "";
    private String THIRD_DEGRESSION_LEVEL = "";
    private String THIRD_DEGRESSION_LEVEL_VALUE_FIX = "";
    private String THIRD_DEGRESSION_LEVEL_VALUE_MOBILE = "";
    private String THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE = "";
    private String FOURTH_DEGRESSION_LEVEL = "";
    private String FOURTH_DEGRESSION_LEVEL_VALUE_FIX = "";
    private String FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE = "";
    private String FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE = "";
    private String FIFTH_DEGRESSION_LEVEL = "";
    private String FIFTH_DEGRESSION_LEVEL_VALUE_FIX = "";
    private String FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE = "";
    private String FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE = "";

    public String getCVO() {
        return CVO;
    }

    public MediaVocal() {
    }

    public MediaVocal(String MEDIA_TYPE, String SUBSCRIPTION_PRICE, String COMMISSIONING_PRICE, String USAGE_PRICE_FIX, String USAGE_PRICE_MOBILE, String USAGE_PRICE_ABOUTE, String FIRST_DEGRESSION_LEVEL, String FIRST_DEGRESSION_LEVEL_VALUE_FIX, String FIRST_DEGRESSION_LEVEL_VALUE_MOBILE, String FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE, String SECOND_DEGRESSION_LEVEL, String SECOND_DEGRESSION_LEVEL_VALUE_FIX, String SECOND_DEGRESSION_LEVEL_VALUE_MOBILE, String SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE, String THIRD_DEGRESSION_LEVEL, String THIRD_DEGRESSION_LEVEL_VALUE_FIX, String THIRD_DEGRESSION_LEVEL_VALUE_MOBILE, String THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE, String FOURTH_DEGRESSION_LEVEL, String FOURTH_DEGRESSION_LEVEL_VALUE_FIX, String FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE, String FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE, String FIFTH_DEGRESSION_LEVEL, String FIFTH_DEGRESSION_LEVEL_VALUE_FIX, String FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE, String FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE) {
        this.MEDIA_TYPE = MEDIA_TYPE;
        this.SUBSCRIPTION_PRICE = SUBSCRIPTION_PRICE;
        this.COMMISSIONING_PRICE = COMMISSIONING_PRICE;
        this.USAGE_PRICE_FIX = USAGE_PRICE_FIX;
        this.USAGE_PRICE_MOBILE = USAGE_PRICE_MOBILE;
        this.USAGE_PRICE_ABOUTE = USAGE_PRICE_ABOUTE;
        this.FIRST_DEGRESSION_LEVEL = FIRST_DEGRESSION_LEVEL;
        this.FIRST_DEGRESSION_LEVEL_VALUE_FIX = FIRST_DEGRESSION_LEVEL_VALUE_FIX;
        this.FIRST_DEGRESSION_LEVEL_VALUE_MOBILE = FIRST_DEGRESSION_LEVEL_VALUE_MOBILE;
        this.FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE = FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE;
        this.SECOND_DEGRESSION_LEVEL = SECOND_DEGRESSION_LEVEL;
        this.SECOND_DEGRESSION_LEVEL_VALUE_FIX = SECOND_DEGRESSION_LEVEL_VALUE_FIX;
        this.SECOND_DEGRESSION_LEVEL_VALUE_MOBILE = SECOND_DEGRESSION_LEVEL_VALUE_MOBILE;
        this.SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE = SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE;
        this.THIRD_DEGRESSION_LEVEL = THIRD_DEGRESSION_LEVEL;
        this.THIRD_DEGRESSION_LEVEL_VALUE_FIX = THIRD_DEGRESSION_LEVEL_VALUE_FIX;
        this.THIRD_DEGRESSION_LEVEL_VALUE_MOBILE = THIRD_DEGRESSION_LEVEL_VALUE_MOBILE;
        this.THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE = THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE;
        this.FOURTH_DEGRESSION_LEVEL = FOURTH_DEGRESSION_LEVEL;
        this.FOURTH_DEGRESSION_LEVEL_VALUE_FIX = FOURTH_DEGRESSION_LEVEL_VALUE_FIX;
        this.FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE = FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE;
        this.FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE = FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE;
        this.FIFTH_DEGRESSION_LEVEL = FIFTH_DEGRESSION_LEVEL;
        this.FIFTH_DEGRESSION_LEVEL_VALUE_FIX = FIFTH_DEGRESSION_LEVEL_VALUE_FIX;
        this.FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE = FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE;
        this.FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE = FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public void setCVO(String CVO) {
        this.CVO = CVO;
    }

    public String getLINE_TYPE() {
        return LINE_TYPE;
    }

    public String getMEDIA_TYPE() {
        return MEDIA_TYPE;
    }

    public void setMEDIA_TYPE(String MEDIA_TYPE) {
        this.MEDIA_TYPE = MEDIA_TYPE;
    }

    public String getSUBSCRIPTION_PRICE() {
        return SUBSCRIPTION_PRICE;
    }

    public void setSUBSCRIPTION_PRICE(String SUBSCRIPTION_PRICE) {
        this.SUBSCRIPTION_PRICE = SUBSCRIPTION_PRICE;
    }

    public String getCOMMISSIONING_PRICE() {
        return COMMISSIONING_PRICE;
    }

    public void setCOMMISSIONING_PRICE(String COMMISSIONING_PRICE) {
        this.COMMISSIONING_PRICE = COMMISSIONING_PRICE;
    }

    public void setLINE_TYPE(String LINE_TYPE) {
        this.LINE_TYPE = LINE_TYPE;
    }

    public String getUSAGE_PRICE_FIX() {
        return USAGE_PRICE_FIX;
    }

    public void setUSAGE_PRICE_FIX(String USAGE_PRICE_FIX) {
        this.USAGE_PRICE_FIX = USAGE_PRICE_FIX;
    }

    public String getUSAGE_PRICE_MOBILE() {
        return USAGE_PRICE_MOBILE;
    }

    public void setUSAGE_PRICE_MOBILE(String USAGE_PRICE_MOBILE) {
        this.USAGE_PRICE_MOBILE = USAGE_PRICE_MOBILE;
    }

    public String getUSAGE_PRICE_ABOUTE() {
        return USAGE_PRICE_ABOUTE;
    }

    public void setUSAGE_PRICE_ABOUTE(String USAGE_PRICE_ABOUTE) {
        this.USAGE_PRICE_ABOUTE = USAGE_PRICE_ABOUTE;
    }

    public String getFIRST_DEGRESSION_LEVEL() {
        return FIRST_DEGRESSION_LEVEL;
    }

    public void setFIRST_DEGRESSION_LEVEL(String FIRST_DEGRESSION_LEVEL) {
        this.FIRST_DEGRESSION_LEVEL = FIRST_DEGRESSION_LEVEL;
    }

    public String getFIRST_DEGRESSION_LEVEL_VALUE_FIX() {
        return FIRST_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public void setFIRST_DEGRESSION_LEVEL_VALUE_FIX(String FIRST_DEGRESSION_LEVEL_VALUE_FIX) {
        this.FIRST_DEGRESSION_LEVEL_VALUE_FIX = FIRST_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public String getFIRST_DEGRESSION_LEVEL_VALUE_MOBILE() {
        return FIRST_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public void setFIRST_DEGRESSION_LEVEL_VALUE_MOBILE(String FIRST_DEGRESSION_LEVEL_VALUE_MOBILE) {
        this.FIRST_DEGRESSION_LEVEL_VALUE_MOBILE = FIRST_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public String getFIRST_DEGRESSION_LEVEL_VALUE_ABOUTE() {
        return FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public void setFIRST_DEGRESSION_LEVEL_VALUE_ABOUTE(String FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE) {
        this.FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE = FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public String getSECOND_DEGRESSION_LEVEL() {
        return SECOND_DEGRESSION_LEVEL;
    }

    public void setSECOND_DEGRESSION_LEVEL(String SECOND_DEGRESSION_LEVEL) {
        this.SECOND_DEGRESSION_LEVEL = SECOND_DEGRESSION_LEVEL;
    }

    public String getSECOND_DEGRESSION_LEVEL_VALUE_FIX() {
        return SECOND_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public void setSECOND_DEGRESSION_LEVEL_VALUE_FIX(String SECOND_DEGRESSION_LEVEL_VALUE_FIX) {
        this.SECOND_DEGRESSION_LEVEL_VALUE_FIX = SECOND_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public String getSECOND_DEGRESSION_LEVEL_VALUE_MOBILE() {
        return SECOND_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public void setSECOND_DEGRESSION_LEVEL_VALUE_MOBILE(String SECOND_DEGRESSION_LEVEL_VALUE_MOBILE) {
        this.SECOND_DEGRESSION_LEVEL_VALUE_MOBILE = SECOND_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public String getSECOND_DEGRESSION_LEVEL_VALUE_ABOUTE() {
        return SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public void setSECOND_DEGRESSION_LEVEL_VALUE_ABOUTE(String SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE) {
        this.SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE = SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public String getTHIRD_DEGRESSION_LEVEL() {
        return THIRD_DEGRESSION_LEVEL;
    }

    public void setTHIRD_DEGRESSION_LEVEL(String THIRD_DEGRESSION_LEVEL) {
        this.THIRD_DEGRESSION_LEVEL = THIRD_DEGRESSION_LEVEL;
    }

    public String getTHIRD_DEGRESSION_LEVEL_VALUE_FIX() {
        return THIRD_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public void setTHIRD_DEGRESSION_LEVEL_VALUE_FIX(String THIRD_DEGRESSION_LEVEL_VALUE_FIX) {
        this.THIRD_DEGRESSION_LEVEL_VALUE_FIX = THIRD_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public String getTHIRD_DEGRESSION_LEVEL_VALUE_MOBILE() {
        return THIRD_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public void setTHIRD_DEGRESSION_LEVEL_VALUE_MOBILE(String THIRD_DEGRESSION_LEVEL_VALUE_MOBILE) {
        this.THIRD_DEGRESSION_LEVEL_VALUE_MOBILE = THIRD_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public String getTHIRD_DEGRESSION_LEVEL_VALUE_ABOUTE() {
        return THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public void setTHIRD_DEGRESSION_LEVEL_VALUE_ABOUTE(String THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE) {
        this.THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE = THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public String getFOURTH_DEGRESSION_LEVEL() {
        return FOURTH_DEGRESSION_LEVEL;
    }

    public void setFOURTH_DEGRESSION_LEVEL(String FOURTH_DEGRESSION_LEVEL) {
        this.FOURTH_DEGRESSION_LEVEL = FOURTH_DEGRESSION_LEVEL;
    }

    public String getFOURTH_DEGRESSION_LEVEL_VALUE_FIX() {
        return FOURTH_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public void setFOURTH_DEGRESSION_LEVEL_VALUE_FIX(String FOURTH_DEGRESSION_LEVEL_VALUE_FIX) {
        this.FOURTH_DEGRESSION_LEVEL_VALUE_FIX = FOURTH_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public String getFOURTH_DEGRESSION_LEVEL_VALUE_MOBILE() {
        return FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public void setFOURTH_DEGRESSION_LEVEL_VALUE_MOBILE(String FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE) {
        this.FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE = FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public String getFOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE() {
        return FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public void setFOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE(String FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE) {
        this.FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE = FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public String getFIFTH_DEGRESSION_LEVEL() {
        return FIFTH_DEGRESSION_LEVEL;
    }

    public void setFIFTH_DEGRESSION_LEVEL(String FIFTH_DEGRESSION_LEVEL) {
        this.FIFTH_DEGRESSION_LEVEL = FIFTH_DEGRESSION_LEVEL;
    }

    public String getFIFTH_DEGRESSION_LEVEL_VALUE_FIX() {
        return FIFTH_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public void setFIFTH_DEGRESSION_LEVEL_VALUE_FIX(String FIFTH_DEGRESSION_LEVEL_VALUE_FIX) {
        this.FIFTH_DEGRESSION_LEVEL_VALUE_FIX = FIFTH_DEGRESSION_LEVEL_VALUE_FIX;
    }

    public String getFIFTH_DEGRESSION_LEVEL_VALUE_MOBILE() {
        return FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public void setFIFTH_DEGRESSION_LEVEL_VALUE_MOBILE(String FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE) {
        this.FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE = FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE;
    }

    public String getFIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE() {
        return FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public void setFIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE(String FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE) {
        this.FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE = FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE;
    }

    public List<String> toStringValues() {
        return Arrays.asList(CVO,LINE_TYPE,MEDIA_TYPE,SUBSCRIPTION_PRICE,COMMISSIONING_PRICE,USAGE_PRICE_FIX,USAGE_PRICE_MOBILE,
                USAGE_PRICE_ABOUTE,FIRST_DEGRESSION_LEVEL,FIRST_DEGRESSION_LEVEL_VALUE_FIX,FIRST_DEGRESSION_LEVEL_VALUE_MOBILE,
                FIRST_DEGRESSION_LEVEL_VALUE_ABOUTE,SECOND_DEGRESSION_LEVEL,SECOND_DEGRESSION_LEVEL_VALUE_FIX,
                SECOND_DEGRESSION_LEVEL_VALUE_MOBILE,SECOND_DEGRESSION_LEVEL_VALUE_ABOUTE,THIRD_DEGRESSION_LEVEL,
                THIRD_DEGRESSION_LEVEL_VALUE_FIX,THIRD_DEGRESSION_LEVEL_VALUE_MOBILE,THIRD_DEGRESSION_LEVEL_VALUE_ABOUTE,
                FOURTH_DEGRESSION_LEVEL,FOURTH_DEGRESSION_LEVEL_VALUE_FIX,FOURTH_DEGRESSION_LEVEL_VALUE_MOBILE,
                FOURTH_DEGRESSION_LEVEL_VALUE_ABOUTE,FIFTH_DEGRESSION_LEVEL,FIFTH_DEGRESSION_LEVEL_VALUE_FIX,
                FIFTH_DEGRESSION_LEVEL_VALUE_MOBILE,FIFTH_DEGRESSION_LEVEL_VALUE_ABOUTE);
    }
}